version: "3"

services:
  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - 8000:8000

  frontend:
    restart: always
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    ports:
      - 3000:3000