// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
  urlSearchParamsBodySerializer,
} from "@hey-api/client-fetch";
import type {
  GetUsersData,
  GetUsersError,
  GetUsersResponse,
  RegisterUserData,
  RegisterUserError,
  RegisterUserResponse,
  DeleteMeData,
  DeleteMeResponse,
  GetMeData,
  GetMeResponse,
  UpdateMeData,
  UpdateMeError,
  UpdateMeResponse,
  DeleteUserByIdData,
  DeleteUserByIdError,
  DeleteUserByIdResponse,
  GetUserByIdData,
  GetUserByIdError,
  GetUserByIdResponse,
  UpdateUserByIdData,
  UpdateUserByIdError,
  UpdateUserByIdResponse,
  LoginData,
  LoginError,
  LoginResponse,
  TestTokenData,
  TestTokenResponse,
  RefreshData,
  RefreshError,
  RefreshResponse,
  CreateLogData,
  CreateLogError,
  CreateLogResponse,
  GetLogsData,
  GetLogsError,
  GetLogsResponse,
  GetLogsHoursData,
  GetLogsHoursError,
  GetLogsHoursResponse,
  GetTotalHoursData,
  GetTotalHoursResponse,
  DeleteLogData,
  DeleteLogError,
  GetLogByIdData,
  GetLogByIdError,
  GetLogByIdResponse,
  EditLogData,
  EditLogError,
  EditLogResponse,
  CreateLeaderboardData,
  CreateLeaderboardError,
  CreateLeaderboardResponse,
  GetOwnedLeaderboardsData,
  GetOwnedLeaderboardsError,
  GetOwnedLeaderboardsResponse,
  GetJoinedLeaderboardsData,
  GetJoinedLeaderboardsError,
  GetJoinedLeaderboardsResponse,
  AddUserData,
  AddUserError,
  AddUserResponse,
  RemoveUserData,
  RemoveUserError,
  RemoveUserResponse,
  RemoveMeData,
  RemoveMeError,
  RemoveMeResponse,
  DeleteLeaderboardData,
  DeleteLeaderboardError,
  GetLeaderboardDataData,
  GetLeaderboardDataError,
  GetLeaderboardDataResponse,
  EditLeaderboardData,
  EditLeaderboardError,
  EditLeaderboardResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Get Users
 * Get all users
 *
 * ** Restricted to superuser **
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetUsersResponse,
    GetUsersError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users",
  });
};

/**
 * Register User
 * Register a new user.
 */
export const registerUser = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    RegisterUserResponse,
    RegisterUserError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/api/v1/users",
  });
};

/**
 * Delete Me
 * Delete current user.
 */
export const deleteMe = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteMeData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteMeResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users/me",
  });
};

/**
 * Get Profile
 * Get current user.
 */
export const getMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetMeResponse, unknown, ThrowOnError>({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users/me",
  });
};

/**
 * Update Profile
 * Update current user
 */
export const updateMe = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMeData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    UpdateMeResponse,
    UpdateMeError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users/me",
  });
};

/**
 * Delete User
 * Delete a user.
 *
 * ** Restricted to superuser **
 */
export const deleteUserById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteUserByIdResponse,
    DeleteUserByIdError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users/{userid}",
  });
};

/**
 * Get User
 * Get User Info
 *
 * ** Restricted to superuser **
 *
 * Parameters
 * ----------
 * userid : UUID
 * the user's UUID
 *
 * Returns
 * -------
 * schemas.User
 * User info
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetUserByIdResponse,
    GetUserByIdError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users/{userid}",
  });
};

/**
 * Update User
 * Update a user.
 *
 * ** Restricted to superuser **
 *
 * Parameters
 * ----------
 * userid : UUID
 * the user's UUID
 * update : schemas.UserUpdate
 * the update data
 * current_user : models.User, optional
 * the current superuser, by default Depends(get_current_active_superuser)
 */
export const updateUserById = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    UpdateUserByIdResponse,
    UpdateUserByIdError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/users/{userid}",
  });
};

/**
 * Create access and refresh tokens for user
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    LoginResponse,
    LoginError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/api/v1/auth/login",
  });
};

/**
 * Test if the access token is valid
 */
export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    TestTokenResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/auth/test-token",
  });
};

/**
 * Refresh token
 */
export const refresh = <ThrowOnError extends boolean = false>(
  options: Options<RefreshData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    RefreshResponse,
    RefreshError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/api/v1/auth/refresh",
  });
};

/**
 * Create Log
 * Create new log for user.
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * start_time: datetime
 * entered start datetime
 *
 * end_time: datetime
 * entered end datetime
 *
 * Returns
 * -------
 * schemas.Log
 * Log info
 */
export const createLog = <ThrowOnError extends boolean = false>(
  options: Options<CreateLogData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateLogResponse,
    CreateLogError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs",
  });
};

/**
 * Get Logs
 * Get all logs for current user
 *
 * ** Restricted to current user **
 */
export const getLogs = <ThrowOnError extends boolean = false>(
  options?: Options<GetLogsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLogsResponse,
    GetLogsError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs/",
  });
};

/**
 * Get Logs Hours
 * Get all logs for current user
 *
 * ** Restricted to current user **
 */
export const getLogsHours = <ThrowOnError extends boolean = false>(
  options?: Options<GetLogsHoursData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLogsHoursResponse,
    GetLogsHoursError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs/logs-hours",
  });
};

/**
 * Get Hours
 */
export const getTotalHours = <ThrowOnError extends boolean = false>(
  options?: Options<GetTotalHoursData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetTotalHoursResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs/hours-total",
  });
};

/**
 * Delete Log
 * Delete a log.
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * logid: UUID
 *
 * Returns
 * -------
 * None
 */
export const deleteLog = <ThrowOnError extends boolean = false>(
  options: Options<DeleteLogData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteLogError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs/{logid}",
  });
};

/**
 * Get Log
 * Create new log for user.
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * logid: UUID
 * The logs id
 *
 * Returns
 * -------
 * schemas.Log
 * Log info
 */
export const getLogById = <ThrowOnError extends boolean = false>(
  options: Options<GetLogByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLogByIdResponse,
    GetLogByIdError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs/{logid}",
  });
};

/**
 * Edit Log
 * Edit a log for user.
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * logid: UUID
 * update: starttime, endtime
 *
 * Returns
 * -------
 * schemas.Log
 * Log info
 */
export const editLog = <ThrowOnError extends boolean = false>(
  options: Options<EditLogData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    EditLogResponse,
    EditLogError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/logs/{logid}",
  });
};

/**
 * Create Leaderboard
 * Creates a new leaderboard
 *
 * ** Restricted to current and logged in user**
 *
 * Parameters
 * ----------
 * leaderboard_name: str, unique
 *
 * Returns
 * -------
 * schemas.Leaderboard
 */
export const createLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<CreateLeaderboardData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateLeaderboardResponse,
    CreateLeaderboardError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards",
  });
};

/**
 * Get Owned Leaderboards
 * Get all leaderboards for current user
 *
 * ** Restricted to current user **
 *
 * Returns
 * -------
 * list schema.Leaderboard
 */
export const getOwnedLeaderboards = <ThrowOnError extends boolean = false>(
  options?: Options<GetOwnedLeaderboardsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetOwnedLeaderboardsResponse,
    GetOwnedLeaderboardsError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/owned",
  });
};

/**
 * Get Joined Leaderboards
 * Get all leaderboards for current user
 *
 * ** Restricted to current user **
 *
 * Returns
 * -------
 * list schema.Leaderboard
 */
export const getJoinedLeaderboards = <ThrowOnError extends boolean = false>(
  options?: Options<GetJoinedLeaderboardsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetJoinedLeaderboardsResponse,
    GetJoinedLeaderboardsError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/joined",
  });
};

/**
 * Add User
 * Add a user to a leaderboard
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * invite_code: str
 * the unique invite code for a leaderboard
 *
 * Returns
 * -------
 * schemas.Leaderboard
 */
export const addUser = <ThrowOnError extends boolean = false>(
  options: Options<AddUserData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    AddUserResponse,
    AddUserError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/add",
  });
};

/**
 * Remove User
 * Remove a user from leaderboard
 *
 * ** Restricted to leaderboard owner **
 *
 * Parameters
 * ----------
 * leaderboardId: UUID,
 * userId: UUID
 *
 * Returns
 * -------
 * schemas.Leaderboard
 */
export const removeUser = <ThrowOnError extends boolean = false>(
  options: Options<RemoveUserData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    RemoveUserResponse,
    RemoveUserError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/remove",
  });
};

/**
 * Remove Me
 * Remove self from leaderboard
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * leaderboardId: UUID,
 *
 * Returns
 * -------
 * schemas.Leaderboard
 */
export const removeMe = <ThrowOnError extends boolean = false>(
  options: Options<RemoveMeData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    RemoveMeResponse,
    RemoveMeError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/remove/me",
  });
};

/**
 * Delete Leaderboard
 * Delete a leaderboard.
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * leaderboardId: UUID
 *
 * Returns
 * -------
 * None
 */
export const deleteLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<DeleteLeaderboardData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteLeaderboardError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/{leaderboardId}",
  });
};

/**
 * Get Leaderboard Data
 * Get a leaderboard users data by it's ID
 *
 * ** Restricted to current user **
 *
 * Parameters
 * ----------
 * leaderboardId: UUID
 *
 * Returns
 * -------
 * list schema.PublicUser
 */
export const getLeaderboardData = <ThrowOnError extends boolean = false>(
  options: Options<GetLeaderboardDataData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetLeaderboardDataResponse,
    GetLeaderboardDataError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/{leaderboardId}",
  });
};

/**
 * Edit Leaderboard
 * Edit a leaderboard
 *
 * ** Restricted to current user/owner of leaderboard **
 *
 * Parameters
 * ----------
 * leaderboardId: UUID
 * update: leaderboard_name, is_active, picture, invite_code
 *
 * Returns
 * -------
 * schemas.Leaderboard
 */
export const editLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<EditLeaderboardData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    EditLeaderboardResponse,
    EditLeaderboardError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        fn: "accessToken",
        in: "header",
        name: "Authorization",
      },
    ],
    url: "/api/v1/leaderboards/{leaderboardId}",
  });
};
