// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_api_v1_auth_login_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_register_user_api_v1_users_post = {
    password: string;
    email: string;
    first_name?: string;
    last_name?: string;
    nick_name?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type TokenSchema = {
    access_token: string;
    refresh_token: string;
};

/**
 * User properties returned by API. Contains private
 * user information such as email, is_active.
 *
 * Should only be returned to admins or self.
 */
export type User = {
    first_name?: (string | null);
    last_name?: (string | null);
    nick_name?: (string | null);
    picture?: (string | null);
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    uuid: string;
};

/**
 * User properties to receive via API on update.
 */
export type UserUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    nick_name?: (string | null);
    picture?: (string | null);
    password?: (string | null);
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RegisterUserApiV1UsersPostData = {
    body: Body_register_user_api_v1_users_post;
};

export type RegisterUserApiV1UsersPostResponse = (User);

export type RegisterUserApiV1UsersPostError = (HTTPValidationError);

export type GetUsersApiV1UsersGetData = {
    query?: {
        limit?: (number | null);
        offset?: (number | null);
    };
};

export type GetUsersApiV1UsersGetResponse = (Array<User>);

export type GetUsersApiV1UsersGetError = (HTTPValidationError);

export type GetProfileApiV1UsersMeGetResponse = (User);

export type GetProfileApiV1UsersMeGetError = unknown;

export type DeleteMeApiV1UsersMeDeleteResponse = (User);

export type DeleteMeApiV1UsersMeDeleteError = unknown;

export type UpdateProfileApiV1UsersMePatchData = {
    body: UserUpdate;
};

export type UpdateProfileApiV1UsersMePatchResponse = (User);

export type UpdateProfileApiV1UsersMePatchError = (HTTPValidationError);

export type UpdateUserApiV1UsersUseridPatchData = {
    body: UserUpdate;
    path: {
        userid: string;
    };
};

export type UpdateUserApiV1UsersUseridPatchResponse = (User);

export type UpdateUserApiV1UsersUseridPatchError = (HTTPValidationError);

export type GetUserApiV1UsersUseridGetData = {
    path: {
        userid: string;
    };
};

export type GetUserApiV1UsersUseridGetResponse = (User);

export type GetUserApiV1UsersUseridGetError = (HTTPValidationError);

export type DeleteUserApiV1UsersUseridDeleteData = {
    path: {
        userid: string;
    };
};

export type DeleteUserApiV1UsersUseridDeleteResponse = (User);

export type DeleteUserApiV1UsersUseridDeleteError = (HTTPValidationError);

export type LoginApiV1AuthLoginPostData = {
    body: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = (TokenSchema);

export type LoginApiV1AuthLoginPostError = (HTTPValidationError);

export type TestTokenApiV1AuthTestTokenPostResponse = (User);

export type TestTokenApiV1AuthTestTokenPostError = unknown;

export type RefreshTokenApiV1AuthRefreshPostData = {
    body: string;
};

export type RefreshTokenApiV1AuthRefreshPostResponse = (TokenSchema);

export type RefreshTokenApiV1AuthRefreshPostError = (HTTPValidationError);